#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ] || [ "$branch" = "dev" ] || [ "$branch" = "master" ]; then
  echo "No hagas commits directos en $branch. Crea una rama personal."
  exit 1
fi
